name: corejourney
description: "PrÃ¤natales Reflextraining App"
publish_to: 'none'
version: 1.0.0+5



environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.0.3
  firebase_remote_config: ^5.0.3
  firebase_crashlytics: ^4.0.3
  firebase_analytics: ^11.0.1
  firebase_performance: ^0.10.0+3
  
  # Local Database & Sync
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.5
  connectivity_plus: ^6.0.3
  
  # UI & Utilities
  go_router: ^14.0.0
  google_fonts: ^6.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Environment Config
  flutter_dotenv: ^5.0.2
  
  # Utils
  equatable: ^2.0.5
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  
  # Security
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  
  # Logging
  logger: ^2.0.2+1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0
  mocktail: ^1.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.staging
    - .env.prod
    - assets/images/
    - assets/images/trainings/moro/
